Protocols:
  BBT_emp:
    SpeakerDiarization:
      All:
        train:
          annotation: /export/fs01/jsalt19/lmarvin/BabyTrain_full/train/all_train.rttm
          annotated: /export/fs01/jsalt19/lmarvin/BabyTrain_full/train/all_train.uem
        development:
          annotation: /export/fs01/jsalt19/lmarvin/BabyTrain_full/dev/all_dev.rttm
          annotated: /export/fs01/jsalt19/lmarvin/BabyTrain_full/dev/all_dev.uem
        test:
          annotation: /export/fs01/jsalt19/lmarvin/BabyTrain_full/test/all_test.rttm
          annotated: /export/fs01/jsalt19/lmarvin/BabyTrain_full/test/all_test.uem
  AMI:
    SpeakerDiarization:
      MixHeadset:
        train:
          annotation: /export/fs01/jsalt19/databases/AMI/train/allMix-Headset_train.rttm
          annotated: /export/fs01/jsalt19/databases/AMI/train/allMix-Headset_train.uem
          domain: /export/b19/mpgill/AMI/domain_ami/domain_input_ami_train.txt
        development:
          annotation: /export/fs01/jsalt19/databases/AMI/dev/allMix-Headset_dev.rttm
          annotated: /export/fs01/jsalt19/databases/AMI/dev/allMix-Headset_dev.uem
          domain: /export/b19/mpgill/AMI/domain_ami/domain_input_ami_dev.txt
        test:
          annotation: /export/fs01/jsalt19/databases/AMI/test/allMix-Headset_test.rttm
          annotated: /export/fs01/jsalt19/databases/AMI/test/allMix-Headset_test.uem
          domain: /export/b19/mpgill/AMI/domain_ami/domain_input_ami_test.txt
  BabyTrain:
    SpeakerDiarization:
      All:
        train:
          annotation: /export/fs01/jsalt19/databases/BabyTrain/train/all_train.rttm
          annotated: /export/fs01/jsalt19/databases/BabyTrain/train/all_train.uem
          domain: /export/b19/mpgill/BabyTrain/domain_input_BabyTrain_train.txt
        development:
          annotation: /export/fs01/jsalt19/databases/BabyTrain/dev/all_dev.rttm
          annotated: /export/fs01/jsalt19/databases/BabyTrain/dev/all_dev.uem
          domain: /export/b19/mpgill/BabyTrain/domain_input_BabyTrain_dev.txt
        test:
          annotation: /export/fs01/jsalt19/databases/BabyTrain/test/all_test.rttm
          annotated: /export/fs01/jsalt19/databases/BabyTrain/test/all_test.uem
          domain: /export/b19/mpgill/BabyTrain/domain_input_BabyTrain_test.txt
      aclewstarter:
        train:
          annotation: /export/fs01/jsalt19/databases/BabyTrain/train/all_train.rttm
          annotated: /export/fs01/jsalt19/databases/BabyTrain/train/all_train.uem
          uris: /export/fs01/jsalt19/databases/BabyTrain/train/aclew_starter_train.txt
        development:
          annotation: /export/fs01/jsalt19/databases/BabyTrain/dev/all_dev.rttm
          annotated: /export/fs01/jsalt19/databases/BabyTrain/dev/all_dev.uem
          uris: /export/fs01/jsalt19/databases/BabyTrain/dev/aclew_starter_dev.txt
        test:
          annotation: /export/fs01/jsalt19/databases/BabyTrain/test/all_test.rttm
          annotated: /export/fs01/jsalt19/databases/BabyTrain/test/all_test.uem
          uris: /export/fs01/jsalt19/databases/BabyTrain/test/aclew_starter_test.txt
      lenalyon:
        train:
          annotation: /export/fs01/jsalt19/databases/BabyTrain/train/all_train.rttm
          annotated: /export/fs01/jsalt19/databases/BabyTrain/train/all_train.uem
          uris: /export/fs01/jsalt19/databases/BabyTrain/train/lena_lyon_train.txt
        development:
          annotation: /export/fs01/jsalt19/databases/BabyTrain/dev/all_dev.rttm
          annotated: /export/fs01/jsalt19/databases/BabyTrain/dev/all_dev.uem
          uris: /export/fs01/jsalt19/databases/BabyTrain/dev/lena_lyon_dev.txt
        test:
          annotation: /export/fs01/jsalt19/databases/BabyTrain/test/all_test.rttm
          annotated: /export/fs01/jsalt19/databases/BabyTrain/test/all_test.uem
          uris: /export/fs01/jsalt19/databases/BabyTrain/test/lena_lyon_test.txt
      namibia:
        train:
          annotation: /export/fs01/jsalt19/databases/BabyTrain/train/all_train.rttm
          annotated: /export/fs01/jsalt19/databases/BabyTrain/train/all_train.uem
          uris: /export/fs01/jsalt19/databases/BabyTrain/train/namibia_train.txt
        development:
          annotation: /export/fs01/jsalt19/databases/BabyTrain/dev/all_dev.rttm
          annotated: /export/fs01/jsalt19/databases/BabyTrain/dev/all_dev.uem
          uris: /export/fs01/jsalt19/databases/BabyTrain/dev/namibia_dev.txt
        test:
          annotation: /export/fs01/jsalt19/databases/BabyTrain/test/all_test.rttm
          annotated: /export/fs01/jsalt19/databases/BabyTrain/test/all_test.uem
          uris: /export/fs01/jsalt19/databases/BabyTrain/test/namibia_test.txt
      paido:
        train:
          annotation: /export/fs01/jsalt19/databases/BabyTrain/train/all_train.rttm
          annotated: /export/fs01/jsalt19/databases/BabyTrain/train/all_train.uem
          uris: /export/fs01/jsalt19/databases/BabyTrain/train/paido_train.txt
        development:
          annotation: /export/fs01/jsalt19/databases/BabyTrain/dev/all_dev.rttm
          annotated: /export/fs01/jsalt19/databases/BabyTrain/dev/all_dev.uem
          uris: /export/fs01/jsalt19/databases/BabyTrain/dev/paido_dev.txt
        test:
          annotation: /export/fs01/jsalt19/databases/BabyTrain/test/all_test.rttm
          annotated: /export/fs01/jsalt19/databases/BabyTrain/test/all_test.uem
          uris: /export/fs01/jsalt19/databases/BabyTrain/test/paido_test.txt
      tsay:
        train:
          annotation: /export/fs01/jsalt19/databases/BabyTrain/train/all_train.rttm
          annotated: /export/fs01/jsalt19/databases/BabyTrain/train/all_train.uem
          uris: /export/fs01/jsalt19/databases/BabyTrain/train/tsay_train.txt
        development:
          annotation: /export/fs01/jsalt19/databases/BabyTrain/dev/all_dev.rttm
          annotated: /export/fs01/jsalt19/databases/BabyTrain/dev/all_dev.uem
          uris: /export/fs01/jsalt19/databases/BabyTrain/dev/tsay_dev.txt
        test:
          annotation: /export/fs01/jsalt19/databases/BabyTrain/test/all_test.rttm
          annotated: /export/fs01/jsalt19/databases/BabyTrain/test/all_test.uem
          uris: /export/fs01/jsalt19/databases/BabyTrain/test/tsay_test.txt
      tsimane:
        train:
          annotation: /export/fs01/jsalt19/databases/BabyTrain/train/all_train.rttm
          annotated: /export/fs01/jsalt19/databases/BabyTrain/train/all_train.uem
          uris: /export/fs01/jsalt19/databases/BabyTrain/train/tsimane_train.txt
        development:
          annotation: /export/fs01/jsalt19/databases/BabyTrain/dev/all_dev.rttm
          annotated: /export/fs01/jsalt19/databases/BabyTrain/dev/all_dev.uem
          uris: /export/fs01/jsalt19/databases/BabyTrain/dev/tsimane_dev.txt
        test:
          annotation: /export/fs01/jsalt19/databases/BabyTrain/test/all_test.rttm
          annotated: /export/fs01/jsalt19/databases/BabyTrain/test/all_test.uem
          uris: /export/fs01/jsalt19/databases/BabyTrain/test/tsimane_test.txt
      vanuatu:
        train:
          annotation: /export/fs01/jsalt19/databases/BabyTrain/train/all_train.rttm
          annotated: /export/fs01/jsalt19/databases/BabyTrain/train/all_train.uem
          uris: /export/fs01/jsalt19/databases/BabyTrain/train/vanuatu_train.txt
        development:
          annotation: /export/fs01/jsalt19/databases/BabyTrain/dev/all_dev.rttm
          annotated: /export/fs01/jsalt19/databases/BabyTrain/dev/all_dev.uem
          uris: /export/fs01/jsalt19/databases/BabyTrain/dev/vanuatu_dev.txt
        test:
          annotation: /export/fs01/jsalt19/databases/BabyTrain/test/all_test.rttm
          annotated: /export/fs01/jsalt19/databases/BabyTrain/test/all_test.uem
          uris: /export/fs01/jsalt19/databases/BabyTrain/test/vanuatu_test.txt
      war2:
        train:
          annotation: /export/fs01/jsalt19/databases/BabyTrain/train/all_train.rttm
          annotated: /export/fs01/jsalt19/databases/BabyTrain/train/all_train.uem
          uris: /export/fs01/jsalt19/databases/BabyTrain/train/war2_train.txt
        development:
          annotation: /export/fs01/jsalt19/databases/BabyTrain/dev/all_dev.rttm
          annotated: /export/fs01/jsalt19/databases/BabyTrain/dev/all_dev.uem
          uris: /export/fs01/jsalt19/databases/BabyTrain/dev/war2_dev.txt
        test:
          annotation: /export/fs01/jsalt19/databases/BabyTrain/test/all_test.rttm
          annotated: /export/fs01/jsalt19/databases/BabyTrain/test/all_test.uem
          uris: /export/fs01/jsalt19/databases/BabyTrain/test/war2_test.txt
  CHiME5:
    SpeakerDiarization:
      U01:
        train:
          annotation: /export/fs01/jsalt19/databases/CHiME5/train/allU01_train.rttm
          annotated: /export/fs01/jsalt19/databases/CHiME5/train/allU01_train.uem
        development:
          annotation: /export/fs01/jsalt19/databases/CHiME5/dev/allU01_dev.rttm
          annotated: /export/fs01/jsalt19/databases/CHiME5/dev/allU01_dev.uem
        test:
          annotation: /export/fs01/jsalt19/databases/CHiME5/test/allU01_test.rttm
          annotated: /export/fs01/jsalt19/databases/CHiME5/test/allU01_test.uem
  SRI:
    SpeakerDiarization:
         #SRI all conds
      All:
         development:
            annotation: /export/fs01/jsalt19/resources/lists/jsalt19_tasks/sri/dev/all_dev.rttm
            annotatated: /export/fs01/jsalt19/resources/lists/jsalt19_tasks/sri/dev/all_dev.uem
         test:
            annotation: /export/fs01/jsalt19/resources/lists/jsalt19_tasks/sri/eval/all_test.rttm
            annotatated: /export/fs01/jsalt19/resources/lists/jsalt19_tasks/sri/dev/all_test.uem
         #SRI close mic
      clo:
         train:
             annotation: /export/fs01/jsalt19/databases/SRI/dev/close_dev.rttm
             annotated: /export/fs01/jsalt19/databases/SRI/dev/close_dev.uem
         development:
             annotation: /export/fs01/jsalt19/databases/SRI/dev/close_dev.rttm
             annotated: /export/fs01/jsalt19/databases/SRI/dev/close_dev.uem
         test:
             annotation: /export/fs01/jsalt19/databases/SRI/test/close_test.rttm
             annotated: /export/fs01/jsalt19/databases/SRI/test/close_test.uem
         #SRI medium mic
      med:
         test:
             annotation: /export/fs01/jsalt19/databases/SRI/test/medium_test.rttm
             annotated: /export/fs01/jsalt19/databases/SRI/test/medium_test.uem
         #SRI far mic
      far:
         development:
             annotation: /export/fs01/jsalt19/databases/SRI/dev/far_dev.rttm
             annotated: /export/fs01/jsalt19/databases/SRI/dev/far_dev.uem
         test:
             annotation: /export/fs01/jsalt19/databases/SRI/test/far_test.rttm
             annotated: /export/fs01/jsalt19/databases/SRI/test/far_test.uem
         #SRI close to radio/tv mic
      tv:
         development:
             annotation: /export/fs01/jsalt19/databases/SRI/dev/close_to_tv_radio_dev.rttm
             annotated: /export/fs01/jsalt19/databases/SRI/dev/close_to_tv_radio_dev.uem
         test:
             annotation: /export/fs01/jsalt19/databases/SRI/test/close_to_tv_radio_test.rttm
             annotated: /export/fs01/jsalt19/databases/SRI/test/close_to_tv_radio_test.uem
         #SRI close + medium mic
      clomed:
         test:
             annotation: /export/fs01/jsalt19/databases/SRI/test/mixed_close_med_test.rttm
             annotated: /export/fs01/jsalt19/databases/SRI/test/mixed_close_med_test.uem
         #SRI close + far + behind the wall mic
      clofarwall:
         test:
             annotation: /export/fs01/jsalt19/databases/SRI/test/mixed_close_far_behind_wall_test.rttm
             annotated: /export/fs01/jsalt19/databases/SRI/test/mixed_close_far_behind_wall_test.uem
  VoxCeleb:
    SpeakerDiarization:
      MaleAugmentation20:
        train:
          annotation: /export/fs01/jsalt19/databases/auxiliary/VoxCeleb/train/all_train.rttm
          annotated: /export/fs01/jsalt19/databases/auxiliary/VoxCeleb/train/all_train.uem
          uris: /export/fs01/jsalt19/databases/auxiliary/VoxCeleb/train/males_20h.txt
        development:
          annotation: /export/fs01/jsalt19/databases/auxiliary/VoxCeleb/dev/all_dev.rttm
          annotated: /export/fs01/jsalt19/databases/auxiliary/VoxCeleb/dev/all_dev.uem
        test:
          annotation: /export/fs01/jsalt19/databases/auxiliary/VoxCeleb/test/all_test.rttm
          annotated: /export/fs01/jsalt19/databases/auxiliary/VoxCeleb/test/all_test.uem
      MaleAugmentation10:
        train:
          annotation: /export/fs01/jsalt19/databases/auxiliary/VoxCeleb/train/all_train.rttm
          annotated: /export/fs01/jsalt19/databases/auxiliary/VoxCeleb/train/all_train.uem
          uris: /export/fs01/jsalt19/databases/auxiliary/VoxCeleb/train/males_10h.txt
        development:
          annotation: /export/fs01/jsalt19/databases/auxiliary/VoxCeleb/dev/all_dev.rttm
          annotated: /export/fs01/jsalt19/databases/auxiliary/VoxCeleb/dev/all_dev.uem
        test:
          annotation: /export/fs01/jsalt19/databases/auxiliary/VoxCeleb/test/all_test.rttm
          annotated: /export/fs01/jsalt19/databases/auxiliary/VoxCeleb/test/all_test.uem
  X:
    SpeakerDiarization:
      BabyTrainAugmentedMale10:
        train:
          BabyTrain.SpeakerDiarization.All: [train]
          VoxCeleb.SpeakerDiarization.MaleAugmentation10: [train]
        development:
          BabyTrain.SpeakerDiarization.All: [development]
        test:
          BabyTrain.SpeakerDiarization.All: [test]
      BabyTrainAugmentedMale20:
        train:
          BabyTrain.SpeakerDiarization.All: [train]
          VoxCeleb.SpeakerDiarization.MaleAugmentation20: [train]
        development:
          BabyTrain.SpeakerDiarization.All: [development]
        test:
          BabyTrain.SpeakerDiarization.All: [test]
Databases:
  BabyTrain: /export/fs01/jsalt19/databases/BabyTrain/*/wav/{uri}.wav
  BBT_emp: /export/fs01/jsalt19/lmarvin/BabyTrain_full/*/wav/{uri}.wav
  AMI: /export/fs01/jsalt19/databases/AMI/*/wav/{uri}.wav
  CHiME5: /export/fs01/jsalt19/databases/CHiME5/*/wav/{uri}.wav
  SRI: /export/fs01/jsalt19/databases/SRI/*/wav/{uri}.wav
  MUSAN: /export/fs01/jsalt19/databases/auxiliary/musan/{uri}.wav
  VoxCeleb: /export/fs01/jsalt19/databases/auxiliary/VoxCeleb/train/wav/{uri}.wav

